sudo: required
language: python
python:
  - '2.7'
  
#install:
#  - pip install -r requirements.txt

services:
  - docker

install:
- docker pull haojieyuan/caffe_training_and_analyzing:cpu

script:
- docker run haojieyuan/caffe_training_and_analyzing:cpu /bin/sh -c  "cd /workspace/Caffe_network_training/Caffe_network_training/test; python test.py"
