sudo: required
language: python
python:
  - '2.7'
  
#install:
#  - pip install -r requirements.txt

services:
  - docker

before_install:
- docker pull haojieyuan/caffe_training_and_analyzing:cpu
- docker run haojieyuan/caffe_training_and_analyzing:cpu /bin/sh -c  "cd /workspace/Caffe_model_analyzer/Caffemodel_analyzier/test; python test.py"

script:
  - ./test/test.py
